### ISSUE TITLE
starting GUI SXP  resolved

### ISSUE THREAD

**Issue by RADOUAabderrahim** [pja35/SXP#3]
following the wiki installation step
an error will appear after this command:

`electron-packager . SXP --platform=darwin --arch=x64 --version=1.2.3`

`
Packaging app for platform darwin x64 using electron v1.2.3
Command failed: npm prune --production
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "prune" "--production"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3

npm ERR! Invalid name: "SXP-network client"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/99/y7_r0ff91vscmyz6hx0m9jkw0000gn/T/electron-packager/darwin-x64/SXP-darwin-x64/Electron.app/Contents/Resources/app/npm-debug.log

`

**Comment by RADOUAabderrahim** [comment]
to solve this problem you have to edit the file  "package.json" in path  "src/main/js"
change the name attribute in file from "SXP-network client" to "SXP"

FROM
`{
    "name": "SXP-network client",
    "version": "0.1.0",
    "main" : "main-electron.js"
}`
TO
`{
    "name": "SXP",
    "version": "0.1.0",
    "main" : "main-electron.js"
}`

and retype the command `electron-packager . SXP --platform=darwin --arch=x64 --version=1.2.3`

**Comment by pja35** [comment]
C'est corrigé

---

Pablo Arrighi
+33611257467
(Sent from my mobile phone.)
